import { Card, CardRole } from "../src/data/cards";

// Role mapping based on category
const categoryRole = (cat: string): CardRole => {
  if (cat === "Dirigeant" || cat === "Dirigeante") return "dirigeant";
  if (cat === "Arbitre" || cat === "Technique/Régional" || cat === "Educateur Fédéral") return "coach";
  return "joueur";
};

const categoryPhoto = (cat: string): string => {
  const role = categoryRole(cat);
  return `/images/roles/${role}.svg`;
};

type RawPlayer = { firstName: string; lastName: string; category: string };

const RAW_PLAYERS: RawPlayer[] = [
  { lastName: "ABRAHAM", firstName: "Damien", category: "Vétéran" },
  { lastName: "ACQUETTE", firstName: "Damien", category: "Vétéran" },
  { lastName: "ANAISE", firstName: "Pierre", category: "Vétéran" },
  { lastName: "BEN ABBES", firstName: "Smail", category: "Vétéran" },
  { lastName: "BOITEL", firstName: "Thibaut", category: "Vétéran" },
  { lastName: "BONDEAU", firstName: "Thierry", category: "Vétéran" },
  { lastName: "BOUTROUILLE", firstName: "Lucas", category: "Vétéran" },
  { lastName: "BRACQBIEN", firstName: "Ludwig", category: "Vétéran" },
  { lastName: "BRACQUART", firstName: "Benoit", category: "Vétéran" },
  { lastName: "CARDON", firstName: "Francois", category: "Vétéran" },
  { lastName: "COCILOVO", firstName: "Alfonso", category: "Vétéran" },
  { lastName: "CRESPEL", firstName: "Aurelien", category: "Vétéran" },
  { lastName: "CZYZ", firstName: "Franck", category: "Vétéran" },
  { lastName: "DALLO", firstName: "Michael", category: "Vétéran" },
  { lastName: "DEBEVRE", firstName: "Sebastien", category: "Vétéran" },
  { lastName: "DECHARRIERE", firstName: "Benoit", category: "Vétéran" },
  { lastName: "DEMAREY", firstName: "Christophe", category: "Vétéran" },
  { lastName: "DESMASURES", firstName: "Baptiste", category: "Vétéran" },
  { lastName: "DEWULF", firstName: "Nicolas", category: "Vétéran" },
  { lastName: "DOIGNIE", firstName: "Loic", category: "Vétéran" },
  { lastName: "DRANCOURT", firstName: "Benjamin", category: "Vétéran" },
  { lastName: "DUTILLEUL", firstName: "Kevin", category: "Vétéran" },
  { lastName: "FERNANDEZ", firstName: "Michael", category: "Vétéran" },
  { lastName: "FOUCHET", firstName: "Sebastien", category: "Vétéran" },
  { lastName: "IBOS", firstName: "Christopher", category: "Vétéran" },
  { lastName: "IBOS", firstName: "Mickael", category: "Vétéran" },
  { lastName: "LECLERCQ", firstName: "Julien", category: "Vétéran" },
  { lastName: "LEROY", firstName: "Raphael", category: "Vétéran" },
  { lastName: "LESAEGE", firstName: "Samuel", category: "Vétéran" },
  { lastName: "LEVY", firstName: "Ruben", category: "Vétéran" },
  { lastName: "LIAGRE", firstName: "Charles Edouard", category: "Vétéran" },
  { lastName: "LONGUEMARE", firstName: "Alexandre", category: "Vétéran" },
  { lastName: "MARQUES", firstName: "Sebastien", category: "Vétéran" },
  { lastName: "MEERE", firstName: "Sylvain", category: "Vétéran" },
  { lastName: "MIKLIN", firstName: "Matthieu", category: "Vétéran" },
  { lastName: "MULLIEZ", firstName: "Louis", category: "Vétéran" },
  { lastName: "OUTIER", firstName: "Christophe", category: "Vétéran" },
  { lastName: "PINTAR", firstName: "Mickael", category: "Vétéran" },
  { lastName: "POIRIER", firstName: "Sebastien", category: "Vétéran" },
  { lastName: "SAUSSOL", firstName: "Matthieu", category: "Vétéran" },
  { lastName: "SLEMBROUCK", firstName: "Pierre", category: "Vétéran" },
  { lastName: "THOUVENIN", firstName: "Nicolas", category: "Vétéran" },
  { lastName: "TONNEL", firstName: "Nicolas", category: "Vétéran" },
  { lastName: "TRACHEZ", firstName: "Benjamin", category: "Vétéran" },
  { lastName: "VAN HONACKER", firstName: "Thomas", category: "Vétéran" },
  { lastName: "VANLITSENBURGH", firstName: "Romain", category: "Vétéran" },
  { lastName: "VASSEUR", firstName: "Anthony", category: "Vétéran" },
  { lastName: "VIGNERON", firstName: "Guillaume", category: "Vétéran" },
  { lastName: "WILLEM", firstName: "Thomas", category: "Vétéran" },
  { lastName: "WILLEMOT", firstName: "Jeremy", category: "Vétéran" },
  { lastName: "WOJTOWICZ", firstName: "Fabrice", category: "Vétéran" },
  { lastName: "BENAOUAG", firstName: "Clement", category: "Senior" },
  { lastName: "BLOTIAU", firstName: "Ethan", category: "Senior" },
  { lastName: "BOCHA WA BOCHA", firstName: "Yliess", category: "Senior" },
  { lastName: "BONDEAU", firstName: "Corentin", category: "Senior" },
  { lastName: "BREC", firstName: "Evan", category: "Senior" },
  { lastName: "CHAPPEY", firstName: "Theo", category: "Senior" },
  { lastName: "DAOUDI", firstName: "Yannis", category: "Senior" },
  { lastName: "DEBRAUWER", firstName: "Maxence", category: "Senior" },
  { lastName: "DEFRANCE", firstName: "Jeremy", category: "Senior" },
  { lastName: "DELPLANQUE", firstName: "Gabin", category: "Senior" },
  { lastName: "DERAEDT", firstName: "Gauthier", category: "Senior" },
  { lastName: "DEZITTER", firstName: "Thomas", category: "Senior" },
  { lastName: "DREVILLE", firstName: "Corentin", category: "Senior" },
  { lastName: "DUCOULOMBIER", firstName: "Jean", category: "Senior" },
  { lastName: "HAIART", firstName: "Lucas", category: "Senior" },
  { lastName: "IMPENS", firstName: "Florian", category: "Senior" },
  { lastName: "KADDECHE", firstName: "Yanis", category: "Senior" },
  { lastName: "LACQUEMENT", firstName: "Baptiste", category: "Senior" },
  { lastName: "LEFEVRE", firstName: "Benjamin", category: "Senior" },
  { lastName: "LEPLUS", firstName: "Guillaume", category: "Senior" },
  { lastName: "NGUYEN", firstName: "Noam", category: "Senior" },
  { lastName: "OUTIER", firstName: "Pierre Louis", category: "Senior" },
  { lastName: "PLUQUET", firstName: "Morgan", category: "Senior" },
  { lastName: "POTTIER", firstName: "Marveen", category: "Senior" },
  { lastName: "SANSICO", firstName: "Tony", category: "Senior" },
  { lastName: "VERHELLEN", firstName: "Maxime", category: "Senior" },
  { lastName: "BONDEAU", firstName: "Valentin", category: "U19" },
  { lastName: "BOUCHART", firstName: "Mathys", category: "U19" },
  { lastName: "DELRUE", firstName: "Adrien", category: "U19" },
  { lastName: "EL OUSROUTI", firstName: "Yanis", category: "U19" },
  { lastName: "GAUTHEROT", firstName: "Augustin", category: "U19" },
  { lastName: "GOZET", firstName: "Mathis", category: "U19" },
  { lastName: "GRANDJEAN", firstName: "Ethan", category: "U19" },
  { lastName: "GRISLAIN", firstName: "Louis", category: "U19" },
  { lastName: "MAQUET", firstName: "Leo", category: "U19" },
  { lastName: "PLUQUET", firstName: "Logan", category: "U18" },
  { lastName: "CARLIER", firstName: "Matthias", category: "U16" },
  { lastName: "CASTIAUX", firstName: "Esteban", category: "U17" },
  { lastName: "CHARLON LEPEZ", firstName: "Arthur", category: "U17" },
  { lastName: "COURSIER", firstName: "Victor", category: "U17" },
  { lastName: "COUSINEAU KLEIN", firstName: "Tanguy", category: "U16" },
  { lastName: "DAERDEN", firstName: "Timote", category: "U16" },
  { lastName: "DAGBERT", firstName: "Thibault", category: "U16" },
  { lastName: "DECLERCQ", firstName: "Mathys", category: "U16" },
  { lastName: "DELBECQ", firstName: "Clement", category: "U17" },
  { lastName: "DELRUE", firstName: "Tom", category: "U16" },
  { lastName: "DEPELCHIN", firstName: "Gino", category: "U17" },
  { lastName: "DESCAMPS", firstName: "Gustin", category: "U17" },
  { lastName: "DESCARPENTRIES", firstName: "Baptiste", category: "U17" },
  { lastName: "DEVIANNE", firstName: "Louis", category: "U16" },
  { lastName: "DUMOULIN", firstName: "Clement", category: "U16" },
  { lastName: "EL YAMANI OUAFKI", firstName: "Mohamed Reda", category: "U17" },
  { lastName: "FICHAUX", firstName: "Jules", category: "U16" },
  { lastName: "FORMENTEL", firstName: "Nathan", category: "U17" },
  { lastName: "FROMONT", firstName: "Mael", category: "U16" },
  { lastName: "GOOSSENS", firstName: "Leandre", category: "U17" },
  { lastName: "GRISLAIN", firstName: "Simon", category: "U16" },
  { lastName: "HENIN", firstName: "Louis", category: "U17" },
  { lastName: "HERMANT", firstName: "Martin", category: "U16" },
  { lastName: "IDIR", firstName: "Noham", category: "U17" },
  { lastName: "KOVES", firstName: "Jules", category: "U17" },
  { lastName: "LAIB", firstName: "Nayles", category: "U16" },
  { lastName: "LAIB", firstName: "Selyan", category: "U17" },
  { lastName: "LERMINEZ", firstName: "Noe", category: "U16" },
  { lastName: "MEULEMANS", firstName: "Theo", category: "U17" },
  { lastName: "MORTIER", firstName: "Theo", category: "U16" },
  { lastName: "MUTO", firstName: "Fabio", category: "U17" },
  { lastName: "NEUSY", firstName: "Ruben", category: "U16" },
  { lastName: "OUTIER", firstName: "Edouard", category: "U17" },
  { lastName: "POURRIER", firstName: "Edgar", category: "U17" },
  { lastName: "ROUSSEAU", firstName: "Thomas", category: "U17" },
  { lastName: "SALERNO", firstName: "Louis Alexandre", category: "U16" },
  { lastName: "SCANNA", firstName: "Remy", category: "U16" },
  { lastName: "SCHEFFLER", firstName: "Zineddine", category: "U16" },
  { lastName: "SCHIPMAN", firstName: "Kylian", category: "U17" },
  { lastName: "SFAR BAUDE", firstName: "Youness", category: "U16" },
  { lastName: "STERCKMAN", firstName: "Louka", category: "U17" },
  { lastName: "TONNEL", firstName: "Thibo", category: "U16" },
  { lastName: "VERQUIN", firstName: "Antoine", category: "U16" },
  { lastName: "VINCKIER", firstName: "Tom", category: "U17" },
  { lastName: "XHAUFLAIR", firstName: "Justin", category: "U16" },
  { lastName: "ZOUARI", firstName: "Elies", category: "U17" },
  { lastName: "BEN ABBES", firstName: "Liam", category: "U14" },
  { lastName: "BOUCLY", firstName: "Aaron", category: "U14" },
  { lastName: "BOURGEOIS", firstName: "Hugo", category: "U14" },
  { lastName: "CAILLE", firstName: "Arthur", category: "U14" },
  { lastName: "CHRETIEN", firstName: "Hugo", category: "U14" },
  { lastName: "EL GHANDOR", firstName: "Ilyass", category: "U15" },
  { lastName: "EL YAMANI OUAFKI", firstName: "Mouhyi", category: "U15" },
  { lastName: "GAIFFE", firstName: "Arnaud", category: "U14" },
  { lastName: "GASSMANN", firstName: "Gianni", category: "U14" },
  { lastName: "GAUTHEROT", firstName: "Simon", category: "U14" },
  { lastName: "GUEYE", firstName: "Mouhamed", category: "U14" },
  { lastName: "LANCRY", firstName: "Johan", category: "U14" },
  { lastName: "LEPOUTRE", firstName: "Basile", category: "U14" },
  { lastName: "LUTYN", firstName: "Mathis", category: "U15" },
  { lastName: "RAOULT", firstName: "Noa", category: "U14" },
  { lastName: "ROUVILLAIN", firstName: "Martin", category: "U14" },
  { lastName: "TUNE", firstName: "Gabriel", category: "U14" },
  { lastName: "VAN AERTENRYCK", firstName: "Clement", category: "U14" },
  { lastName: "VREVIN", firstName: "Hugo", category: "U14" },
  { lastName: "BARAN", firstName: "Jan", category: "U13" },
  { lastName: "BARANEK", firstName: "Tinao", category: "U12" },
  { lastName: "BOUCHER", firstName: "Nathan", category: "U12" },
  { lastName: "BRAURE", firstName: "Lucien", category: "U13" },
  { lastName: "BROEHL", firstName: "Yann", category: "U13" },
  { lastName: "CATRIX", firstName: "Martin", category: "U12" },
  { lastName: "DASSONVILLE", firstName: "Charlie", category: "U13" },
  { lastName: "DE CASTRO", firstName: "Elio", category: "U13" },
  { lastName: "DE KNUYT", firstName: "Axel", category: "U13" },
  { lastName: "DELAHAYE", firstName: "Tommy", category: "U12" },
  { lastName: "DESMET", firstName: "Clement", category: "U12" },
  { lastName: "DESROUSSEAUX", firstName: "Clement", category: "U12" },
  { lastName: "DUFLOT", firstName: "Tom", category: "U13" },
  { lastName: "DURIEUX", firstName: "Evann", category: "U13" },
  { lastName: "FRANCHOMME", firstName: "Simon", category: "U13" },
  { lastName: "FRUIET", firstName: "Simon", category: "U13" },
  { lastName: "GAESTEL", firstName: "Oscar", category: "U12" },
  { lastName: "GRAND JEAN", firstName: "Aronn", category: "U13" },
  { lastName: "LAIB", firstName: "Noam", category: "U12" },
  { lastName: "LANDOUZY", firstName: "Mathis", category: "U13" },
  { lastName: "LEBLANC", firstName: "Louis", category: "U13" },
  { lastName: "LECOCQ JOSEPH", firstName: "Edgar", category: "U12" },
  { lastName: "LETRILLARD", firstName: "Natanel", category: "U13" },
  { lastName: "MALESIEUX CHON", firstName: "Soan", category: "U12" },
  { lastName: "PICAVET", firstName: "Leon", category: "U13" },
  { lastName: "REANT", firstName: "Baptiste", category: "U13" },
  { lastName: "ROTY", firstName: "Sacha", category: "U13" },
  { lastName: "SCHIPMAN", firstName: "Nolann", category: "U13" },
  { lastName: "VAN HONACKER", firstName: "Tom", category: "U12" },
  { lastName: "VANTIGHEM", firstName: "Mathis", category: "U13" },
  { lastName: "VIGIN ROGER", firstName: "Marceau", category: "U12" },
  { lastName: "AKTEN", firstName: "Leo", category: "U8" },
  { lastName: "ALTOMARE", firstName: "Gaspard", category: "U6" },
  { lastName: "ALTOMARE", firstName: "Isaac", category: "U10" },
  { lastName: "ANAISE", firstName: "Victor", category: "U10" },
  { lastName: "ANGIBAUD", firstName: "Donovan", category: "U11" },
  { lastName: "BAILLY", firstName: "Owen", category: "U8" },
  { lastName: "BALLIEU", firstName: "Maxime", category: "U8" },
  { lastName: "BEAUVAIS", firstName: "Camille", category: "U7" },
  { lastName: "BECQUART BOUNSAYTHIP", firstName: "Henri", category: "U7" },
  { lastName: "BEQUART", firstName: "Antoine", category: "U11" },
  { lastName: "BERTOUX STAHL", firstName: "Gabriel", category: "U7" },
  { lastName: "BLOMME", firstName: "Paul", category: "U7" },
  { lastName: "BONVIN", firstName: "Augustin", category: "U8" },
  { lastName: "BRACQBIEN", firstName: "Conor", category: "U8" },
  { lastName: "BRACQUART", firstName: "Maxime", category: "U10" },
  { lastName: "BRUNELIERE", firstName: "Antoine", category: "U10" },
  { lastName: "CATRIX", firstName: "Marin", category: "U9" },
  { lastName: "CATRIX", firstName: "Paul", category: "U9" },
  { lastName: "CHARTIER LANVIN", firstName: "Timotee", category: "U7" },
  { lastName: "COLLIER", firstName: "Leo", category: "U7" },
  { lastName: "CORNUAU", firstName: "Hugo", category: "U11" },
  { lastName: "DA COSTA", firstName: "Antoine", category: "U10" },
  { lastName: "DE FREITAS", firstName: "Leo", category: "U6" },
  { lastName: "DEBEVRE LE", firstName: "Eliam", category: "U8" },
  { lastName: "DELECLUSE", firstName: "Enzo", category: "U6" },
  { lastName: "DELEHAYE", firstName: "Hugo", category: "U10" },
  { lastName: "DELESALLE", firstName: "Romeo", category: "U9" },
  { lastName: "DESMET", firstName: "Timothee", category: "U7" },
  { lastName: "DESPLECHIN", firstName: "Gaspard", category: "U9" },
  { lastName: "DRANCOURT", firstName: "Ezechiel", category: "U11" },
  { lastName: "EL YAMANI OUAFKI", firstName: "Saad Eddin", category: "U10" },
  { lastName: "EVERAERT", firstName: "Romain", category: "U11" },
  { lastName: "FIGUEIRA", firstName: "Raphael", category: "U11" },
  { lastName: "FORMENTEL", firstName: "Eliott", category: "U11" },
  { lastName: "FRAJ", firstName: "Mohamed", category: "U7" },
  { lastName: "GRANDJEAN", firstName: "Natan", category: "U7" },
  { lastName: "JESSON", firstName: "Robin", category: "U7" },
  { lastName: "JESSON", firstName: "Tristan", category: "U9" },
  { lastName: "KHAIF", firstName: "Ilyes", category: "U11" },
  { lastName: "LADU", firstName: "Robin", category: "U10" },
  { lastName: "LANDOUZY", firstName: "Clement", category: "U7" },
  { lastName: "LASKY", firstName: "Destan", category: "U9" },
  { lastName: "LECLERCQ", firstName: "Leandre", category: "U10" },
  { lastName: "LECLERCQ", firstName: "Pierre Alexandre", category: "U11" },
  { lastName: "LECOCQ JOSEPH", firstName: "Barnabe", category: "U10" },
  { lastName: "LEGRAND", firstName: "Anatole", category: "U8" },
  { lastName: "LEGRAND", firstName: "Thibault", category: "U10" },
  { lastName: "LEMAIRE", firstName: "Louis", category: "U10" },
  { lastName: "LEMOINE", firstName: "Noah", category: "U9" },
  { lastName: "LEROY", firstName: "Timeo", category: "U11" },
  { lastName: "LEROY", firstName: "Tom", category: "U8" },
  { lastName: "LEVY", firstName: "Ethan", category: "U7" },
  { lastName: "LIENARD", firstName: "Leonard", category: "U7" },
  { lastName: "LONGUEMARE", firstName: "Victor", category: "U10" },
  { lastName: "MAQUET", firstName: "Antoine", category: "U6" },
  { lastName: "MARC", firstName: "Oscar", category: "U8" },
  { lastName: "MICHAUX", firstName: "Louis", category: "U8" },
  { lastName: "MIKLIN", firstName: "Lucien", category: "U8" },
  { lastName: "NEDELEC", firstName: "Hugo", category: "U8" },
  { lastName: "PAVAUT KERJOSE", firstName: "Leandre", category: "U11" },
  { lastName: "PIGNON", firstName: "Bastien", category: "U6" },
  { lastName: "PIGNON", firstName: "Romain", category: "U8" },
  { lastName: "ROCHE", firstName: "Martin", category: "U7" },
  { lastName: "ROUVILLAIN", firstName: "Jean", category: "U9" },
  { lastName: "ROUYET", firstName: "Hamza", category: "U11" },
  { lastName: "SAUVAGE", firstName: "Gabriel", category: "U10" },
  { lastName: "SLEMBROUCK", firstName: "Thao Sai", category: "U10" },
  { lastName: "TASSANI", firstName: "Domitil", category: "U9" },
  { lastName: "TRACHEZ", firstName: "Telio", category: "U10" },
  { lastName: "TRACHEZ", firstName: "Timael", category: "U6" },
  { lastName: "VAN HONACKER", firstName: "Nathan", category: "U9" },
  { lastName: "VIGNERON", firstName: "Thibault", category: "U9" },
  { lastName: "VINCENT", firstName: "Soren", category: "U8" },
  { lastName: "WAREIN", firstName: "Achille", category: "U9" },
  { lastName: "WHITEHEAD", firstName: "Sacha", category: "U9" },
  { lastName: "BRAURE", firstName: "Audrey", category: "Senior F" },
  { lastName: "CORDIER", firstName: "Charlotte", category: "Senior F" },
  { lastName: "DESPLECHIN", firstName: "Stephanie", category: "Senior F" },
  { lastName: "DUCROUX", firstName: "Delphine", category: "Senior F" },
  { lastName: "DUFERMONT", firstName: "Isabelle", category: "Senior F" },
  { lastName: "FOUTRY", firstName: "Marie", category: "Senior F" },
  { lastName: "GOY", firstName: "Floriane", category: "Senior F" },
  { lastName: "HERMEL", firstName: "Julie", category: "Senior F" },
  { lastName: "JULLIEN", firstName: "Elodie", category: "Senior F" },
  { lastName: "LEBLANC", firstName: "Rachida", category: "Senior F" },
  { lastName: "BEQUART", firstName: "Cloe", category: "U16 F" },
  { lastName: "DAMMAK", firstName: "Emelia Amel", category: "U18 F" },
  { lastName: "DELBEKE", firstName: "Leontine", category: "U16 F" },
  { lastName: "DELERUE", firstName: "Manon", category: "U17 F" },
  { lastName: "DESGRUGILLERS", firstName: "Alice", category: "U16 F" },
  { lastName: "DIANA", firstName: "Chloe", category: "U18 F" },
  { lastName: "DUHNING", firstName: "Luna", category: "U18 F" },
  { lastName: "FLUHR", firstName: "Clara", category: "U18 F" },
  { lastName: "GANNE", firstName: "Celeyne", category: "U17 F" },
  { lastName: "HERBAUT", firstName: "Emma", category: "U17 F" },
  { lastName: "HERBAUT", firstName: "Zelia", category: "U18 F" },
  { lastName: "HIOLLE", firstName: "Lilou", category: "U17 F" },
  { lastName: "LETRILLARD", firstName: "Yona", category: "U16 F" },
  { lastName: "MAHER", firstName: "Amelie", category: "U18 F" },
  { lastName: "SCHEFFLER", firstName: "Assiya", category: "U17 F" },
  { lastName: "THINON", firstName: "Clemence", category: "U17 F" },
  { lastName: "VAN MULLEM", firstName: "Cloe", category: "U16 F" },
  { lastName: "VANDESTIENNE", firstName: "Lena", category: "U17 F" },
  { lastName: "VANLOOT", firstName: "Noemie", category: "U18 F" },
  { lastName: "VELS", firstName: "Lea", category: "U17 F" },
  { lastName: "ASISCLO", firstName: "Lily", category: "U14 F" },
  { lastName: "BELPALME", firstName: "Rachel", category: "U14 F" },
  { lastName: "BOYER", firstName: "Celeste", category: "U14 F" },
  { lastName: "BRUN", firstName: "Astrid", category: "U15 F" },
  { lastName: "BULLETEAU", firstName: "Lola", category: "U14 F" },
  { lastName: "COSTA", firstName: "Soline", category: "U14 F" },
  { lastName: "DA SILVA LEAL", firstName: "Sasha", category: "U15 F" },
  { lastName: "DEMAREY", firstName: "Emma", category: "U14 F" },
  { lastName: "DEVILDER", firstName: "Raphaelle", category: "U15 F" },
  { lastName: "LADU", firstName: "Sophie", category: "U15 F" },
  { lastName: "MASSE", firstName: "Camille", category: "U14 F" },
  { lastName: "MONCOMBLE", firstName: "Andrea", category: "U14 F" },
  { lastName: "REYNS", firstName: "Maelle", category: "U14 F" },
  { lastName: "STOFFAES", firstName: "Camille", category: "U15 F" },
  { lastName: "SUISSA DEWULF", firstName: "Zia", category: "U15 F" },
  { lastName: "VERLEYEN", firstName: "Camille", category: "U14 F" },
  { lastName: "BLOMME", firstName: "Louise", category: "U12 F" },
  { lastName: "BONDEAU", firstName: "Ava", category: "U13 F" },
  { lastName: "BONNEL", firstName: "Lucile", category: "U12 F" },
  { lastName: "BOUJLLAOUI", firstName: "Jihad", category: "U12 F" },
  { lastName: "DELBECQ", firstName: "Zoe", category: "U12 F" },
  { lastName: "DELCOURT", firstName: "Zoe", category: "U13 F" },
  { lastName: "DEMAS", firstName: "Axelle", category: "U12 F" },
  { lastName: "DEMONCHAUX GREMEL", firstName: "Ines", category: "U12 F" },
  { lastName: "DESSEAUX", firstName: "Axelle", category: "U13 F" },
  { lastName: "DUFURIER", firstName: "Lisa", category: "U13 F" },
  { lastName: "FAREZ", firstName: "Celia", category: "U13 F" },
  { lastName: "FAVELLA", firstName: "Sarah", category: "U13 F" },
  { lastName: "FRASSINT", firstName: "Victoire", category: "U12 F" },
  { lastName: "GALLEGO", firstName: "Charlotte", category: "U12 F" },
  { lastName: "GERILS", firstName: "Daphne", category: "U13 F" },
  { lastName: "KHABZAOUI", firstName: "Zahra", category: "U13 F" },
  { lastName: "KREMER", firstName: "Anna", category: "U12 F" },
  { lastName: "MONTANT", firstName: "Eleonore", category: "U13 F" },
  { lastName: "MORTIER", firstName: "Noemie", category: "U13 F" },
  { lastName: "PARSY", firstName: "Clara", category: "U12 F" },
  { lastName: "PLANCQ", firstName: "Lily", category: "U12 F" },
  { lastName: "SCRIVE", firstName: "Angelina", category: "U13 F" },
  { lastName: "SLEMBROUCK", firstName: "Lily Mai", category: "U12 F" },
  { lastName: "BERTOUX STAHL", firstName: "Louise", category: "U10 F" },
  { lastName: "BONDEAU", firstName: "Zoa", category: "U9 F" },
  { lastName: "BRAURE", firstName: "Octavie", category: "U10 F" },
  { lastName: "CARRETTE MERLIN", firstName: "Eloise", category: "U6 F" },
  { lastName: "CATRIX", firstName: "Maelle", category: "U11 F" },
  { lastName: "DROUIN", firstName: "Anaelle", category: "U10 F" },
  { lastName: "FIQUOY", firstName: "Myrtille", category: "U11 F" },
  { lastName: "LESAEGE", firstName: "Julia", category: "U10 F" },
  { lastName: "PTASZYNSKI", firstName: "Mya", category: "U10 F" },
  { lastName: "RINGUET", firstName: "Valentine", category: "U6 F" },
  { lastName: "SUBIGER DUHAMEL", firstName: "Romane", category: "U9 F" },
  { lastName: "VINCENT", firstName: "Lou", category: "U11 F" },
  { lastName: "WETZEL", firstName: "Elise", category: "U10 F" },
  { lastName: "WHITEHEAD", firstName: "Alix", category: "U6 F" },
  { lastName: "BACQUET", firstName: "Ancelin", category: "Foot Loisir" },
  { lastName: "BILLET", firstName: "Alexandre", category: "Foot Loisir" },
  { lastName: "BRILLON", firstName: "Baptiste", category: "Foot Loisir" },
  { lastName: "CHARTIER", firstName: "Pierrick", category: "Foot Loisir" },
  { lastName: "CHARTIER", firstName: "Yoann", category: "Foot Loisir" },
  { lastName: "DEBEVE", firstName: "Axel", category: "Foot Loisir" },
  { lastName: "DESCHILDRE", firstName: "Raphael", category: "Foot Loisir" },
  { lastName: "DUBOIS", firstName: "Julien", category: "Foot Loisir" },
  { lastName: "DUMEZ", firstName: "Pirlouit", category: "Foot Loisir" },
  { lastName: "GOSSELIN", firstName: "Julien", category: "Foot Loisir" },
  { lastName: "LAVAL", firstName: "Quentin", category: "Foot Loisir" },
  { lastName: "LEFEBVRE", firstName: "Samuel", category: "Foot Loisir" },
  { lastName: "MABRIER", firstName: "Quentin", category: "Foot Loisir" },
  { lastName: "MARECAUX", firstName: "Nicolas", category: "Foot Loisir" },
  { lastName: "PASQUET", firstName: "Mathieu Pierre", category: "Foot Loisir" },
  { lastName: "PLAYE", firstName: "Marvin", category: "Foot Loisir" },
  { lastName: "PODDA", firstName: "Victor", category: "Foot Loisir" },
  { lastName: "SEINGIER", firstName: "Pierre", category: "Foot Loisir" },
  { lastName: "TABTI", firstName: "Joaquim", category: "Foot Loisir" },
  { lastName: "WATRELOT", firstName: "Julien", category: "Foot Loisir" },
  { lastName: "ALTOMARE", firstName: "Nicolas", category: "Dirigeant" },
  { lastName: "BONDEAU", firstName: "Corentin", category: "Dirigeant" },
  { lastName: "BONDEAU", firstName: "Thierry", category: "Dirigeant" },
  { lastName: "BUTIN", firstName: "Didier", category: "Dirigeant" },
  { lastName: "CASTIAUX", firstName: "Sebastien", category: "Dirigeant" },
  { lastName: "CHAILLET", firstName: "Maxime", category: "Dirigeant" },
  { lastName: "CORNUAU", firstName: "Guillaume", category: "Dirigeant" },
  { lastName: "COULON", firstName: "Patrice", category: "Dirigeant" },
  { lastName: "CURNELLE", firstName: "Jimmy", category: "Dirigeant" },
  { lastName: "DEBRAUWER", firstName: "Maxence", category: "Dirigeant" },
  { lastName: "DELCOURT", firstName: "Gilles", category: "Dirigeant" },
  { lastName: "DELPLANQUE", firstName: "Gabin", category: "Dirigeant" },
  { lastName: "DELRUE", firstName: "Adrien", category: "Dirigeant" },
  { lastName: "DELRUE", firstName: "Patrick", category: "Dirigeant" },
  { lastName: "DEMAREY", firstName: "Christophe", category: "Dirigeant" },
  { lastName: "DESCARPENTRIES", firstName: "Florian", category: "Dirigeant" },
  { lastName: "DESTAILLEURS", firstName: "Jacky", category: "Dirigeant" },
  { lastName: "DEZITTER", firstName: "Thomas", category: "Dirigeant" },
  { lastName: "DUTHOIT", firstName: "Maxime", category: "Dirigeant" },
  { lastName: "DUTHOIT", firstName: "Richard", category: "Dirigeant" },
  { lastName: "FIGUEIRA", firstName: "Adrien", category: "Dirigeant" },
  { lastName: "FOURET", firstName: "Lucas", category: "Dirigeant" },
  { lastName: "FRANCOIS", firstName: "Martin", category: "Dirigeant" },
  { lastName: "FRANQUET", firstName: "Mickael", category: "Dirigeant" },
  { lastName: "FROMONT", firstName: "Jerome", category: "Dirigeant" },
  { lastName: "FRUIET", firstName: "David", category: "Dirigeant" },
  { lastName: "GALLEGO", firstName: "Yoann", category: "Dirigeant" },
  { lastName: "GRANDJEAN", firstName: "Tony", category: "Dirigeant" },
  { lastName: "GRISLAIN", firstName: "Alexandre", category: "Dirigeant" },
  { lastName: "HELEVAUT", firstName: "Simon", category: "Dirigeant" },
  { lastName: "LADU", firstName: "Arnaud", category: "Dirigeant" },
  { lastName: "LAROUBI", firstName: "Abdelkader", category: "Dirigeant" },
  { lastName: "LAVAL", firstName: "Quentin", category: "Dirigeant" },
  { lastName: "LECOCQ", firstName: "Alban", category: "Dirigeant" },
  { lastName: "LECOMTE", firstName: "Stephane", category: "Dirigeant" },
  { lastName: "MALESIEUX", firstName: "Jean Luc", category: "Dirigeant" },
  { lastName: "MARLIER", firstName: "Theo", category: "Dirigeant" },
  { lastName: "MARTIN", firstName: "Vincent", category: "Dirigeant" },
  { lastName: "MOLLET", firstName: "Alain", category: "Dirigeant" },
  { lastName: "SCHEFFLER", firstName: "Regis", category: "Dirigeant" },
  { lastName: "THOUVENIN", firstName: "Nicolas", category: "Dirigeant" },
  { lastName: "TOUTAIN", firstName: "Edouard", category: "Dirigeant" },
  { lastName: "TRACHEZ", firstName: "Benjamin", category: "Dirigeant" },
  { lastName: "VAN MULLEM", firstName: "Nicolas", category: "Dirigeant" },
  { lastName: "VERHELLEN", firstName: "Maxime", category: "Dirigeant" },
  { lastName: "VERLEYEN", firstName: "Jerome", category: "Dirigeant" },
  { lastName: "WILLEMOT", firstName: "Jeremy", category: "Dirigeant" },
  { lastName: "BONDEAU", firstName: "Severine", category: "Dirigeante" },
  { lastName: "BONNEL", firstName: "Maelle", category: "Dirigeante" },
  { lastName: "DE COSTER", firstName: "Helene", category: "Dirigeante" },
  { lastName: "DELCOURT", firstName: "Aurelie", category: "Dirigeante" },
  { lastName: "DEMAREY", firstName: "Catherine", category: "Dirigeante" },
  { lastName: "GALLEGO", firstName: "Aline", category: "Dirigeante" },
  { lastName: "HERBAUT", firstName: "Julie", category: "Dirigeante" },
  { lastName: "KHOBZAOUI", firstName: "Samia", category: "Dirigeante" },
  { lastName: "LEMAIRE", firstName: "Charlotte", category: "Dirigeante" },
  { lastName: "LEPEZ", firstName: "Laureen", category: "Dirigeante" },
  { lastName: "LIVEMONT", firstName: "Cyllia", category: "Dirigeante" },
  { lastName: "MONTANT", firstName: "Meredith", category: "Dirigeante" },
  { lastName: "SERGIANI", firstName: "Lina", category: "Dirigeante" },
  { lastName: "DUTERTE", firstName: "Rudy", category: "Arbitre" },
  { lastName: "ELACHI", firstName: "Mohamed", category: "Arbitre" },
  { lastName: "IRACI", firstName: "Tony", category: "Arbitre" },
  { lastName: "CHANTEMARGUE", firstName: "Gabriel", category: "Technique/Régional" },
  { lastName: "DEVLEESSCHAUWER", firstName: "Gwenaelle", category: "Technique/Régional" },
  { lastName: "BONDEAU", firstName: "Nicolas", category: "Educateur Fédéral" },
  { lastName: "BONDEAU", firstName: "Thierry", category: "Educateur Fédéral" },
  { lastName: "BUTIN", firstName: "Didier", category: "Educateur Fédéral" },
  { lastName: "DELBARRE", firstName: "Cyril", category: "Educateur Fédéral" },
  { lastName: "DUTHOIT", firstName: "Sebastien", category: "Educateur Fédéral" },
  { lastName: "LANCRY", firstName: "Claude", category: "Educateur Fédéral" },
  { lastName: "MAQUET", firstName: "Frederic", category: "Educateur Fédéral" },
  { lastName: "VAN HONACKER", firstName: "Thomas", category: "Educateur Fédéral" },
];

export const seedClubCards = (): Card[] => {
  const cards: Card[] = [];

  RAW_PLAYERS.forEach((player, index) => {
    const role = categoryRole(player.category);
    const id = `${role}-${(index + 1).toString().padStart(3, "0")}`;

    cards.push({
      id,
      firstName: player.firstName,
      lastName: player.lastName,
      role,
      category: player.category,
      number: index + 1,
      team: "ECC Panini",
      photo: categoryPhoto(player.category),
    });
  });

  return cards;
};

if (require.main === module) {
  const cards = seedClubCards();
  console.log(`Seed prêt: ${cards.length} cartes`);
}