import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken, getTokenFromHeader } from '@/lib/auth';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  try {
    const token = getTokenFromHeader(request.headers.get('authorization') || '');
    if (!token) {
      return NextResponse.json({ error: 'Non authentifié' }, { status: 401 });
    }

    const decoded = verifyToken(token);
    if (!decoded) {
      return NextResponse.json({ error: 'Token invalide' }, { status: 401 });
    }

    // Fetch daily quests generated by cron (those with date key pattern)
    const userQuests = await prisma.userQuest.findMany({
      where: { userId: decoded.userId },
      orderBy: { createdAt: 'desc' },
    });

    // Also fetch pool metadata for each quest
    const poolKeys = [...new Set(userQuests.map((q) => {
      // Extract the pool key from questId (format: poolKey_YYYYMMDD)
      const parts = q.questId.split('_');
      return parts.slice(0, -1).join('_');
    }).filter(Boolean))];

    const poolQuests = poolKeys.length > 0
      ? await prisma.questPool.findMany({ where: { key: { in: poolKeys } } })
      : [];

    const poolMap = new Map(poolQuests.map((p) => [p.key, p]));

    const dailyQuests = userQuests
      .filter((uq) => uq.questId.includes('_') && uq.questId.split('_').pop()?.length === 8)
      .map((uq) => {
        const poolKey = uq.questId.split('_').slice(0, -1).join('_');
        const pool = poolMap.get(poolKey);
        return {
          id: uq.questId,
          title: pool?.title ?? 'Quête',
          description: pool?.description ?? '',
          type: pool?.type ?? 'UNKNOWN',
          target: uq.target,
          rewardTokens: 5,
          progress: uq.progress,
          completed: uq.completed,
          rewardClaimed: uq.rewardClaimed,
          isDaily: true,
        };
      });

    return NextResponse.json({ quests: dailyQuests });
  } catch (error) {
    console.error('Quests error:', error);
    return NextResponse.json({ error: 'Erreur lors de la récupération des quêtes' }, { status: 500 });
  }
}
