import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken, getTokenFromHeader } from '@/lib/auth';
import { FALLBACK_QUESTS } from '@/data/fallbackQuests';
import { QUEST_DEFINITIONS } from '@/data/quests';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  try {
    const token = getTokenFromHeader(request.headers.get('authorization') || '');
    if (!token) {
      return NextResponse.json({ error: 'Non authentifié' }, { status: 401 });
    }

    const decoded = verifyToken(token);
    if (!decoded) {
      return NextResponse.json({ error: 'Token invalide' }, { status: 401 });
    }

    const userId = decoded.userId;

    // Fetch user stats for progress tracking
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: {
        totalBoostersOpened: true,
        totalRecycles: true,
        totalCardsObtained: true,
      },
    });

    // Fetch all UserQuest records for this user
    const userQuests = await prisma.userQuest.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
    });

    console.log(`[quests API] userId=${userId} total UserQuest records: ${userQuests.length}`);
    userQuests.forEach(uq => console.log(`  - ${uq.questId} progress=${uq.progress}/${uq.target} completed=${uq.completed} claimed=${uq.rewardClaimed}`));

    // --- 1. Daily quests (generated by cron, questId has _YYYYMMDD suffix) ---
    const dailyQuests = userQuests
      .filter((uq) => uq.questId.includes('_') && uq.questId.split('_').pop()?.length === 8);

    const poolKeys = [...new Set(dailyQuests.map((q) => {
      const parts = q.questId.split('_');
      return parts.slice(0, -1).join('_');
    }).filter(Boolean))];

    const poolQuests = poolKeys.length > 0
      ? await prisma.questPool.findMany({ where: { key: { in: poolKeys } } })
      : [];

    const poolMap = new Map(poolQuests.map((p) => [p.key, p]));

    const daily = dailyQuests.map((uq) => {
      const poolKey = uq.questId.split('_').slice(0, -1).join('_');
      const pool = poolMap.get(poolKey);
      return {
        id: uq.questId,
        title: pool?.title ?? 'Quête',
        description: pool?.description ?? '',
        type: pool?.type ?? 'UNKNOWN',
        target: uq.target,
        rewardTokens: 5,
        rewardBoosters: 0,
        progress: uq.progress,
        completed: uq.completed,
        rewardClaimed: uq.rewardClaimed,
        isDaily: true,
      };
    });

    // --- 2. Permanent quests from QUEST_DEFINITIONS with UserQuest progress ---
    const defQuestIds = QUEST_DEFINITIONS.map(d => d.id);
    const defUserQuests = userQuests.filter(uq => defQuestIds.includes(uq.questId));
    const uqMap = new Map(defUserQuests.map(q => [q.questId, q]));

    const permanent = QUEST_DEFINITIONS.map(def => {
      const uq = uqMap.get(def.id);

      // Auto-sync progress from user stats
      let baseProgress = uq?.progress ?? 0;
      if (def.type === 'booster_count') {
        baseProgress = Math.max(baseProgress, user?.totalBoostersOpened ?? 0);
      } else if (def.type === 'recycle_count') {
        baseProgress = Math.max(baseProgress, user?.totalRecycles ?? 0);
      } else if (def.type === 'unique_count') {
        baseProgress = Math.max(baseProgress, user?.totalCardsObtained ?? 0);
      }

      return {
        id: def.id,
        title: def.title,
        description: def.description,
        type: def.type,
        target: def.target,
        rewardTokens: 0,
        rewardBoosters: def.rewardBoosters,
        progress: baseProgress,
        completed: baseProgress >= def.target,
        rewardClaimed: uq?.rewardClaimed ?? false,
        isDaily: false,
      };
    });

    console.log(`[quests API] daily=${daily.length} permanent=${permanent.length}`);

    // --- 3. Fallback / other persisted quests (e.g. fallback_booster_1) ---
    const knownIds = new Set([...defQuestIds, ...daily.map(q => q.id)]);
    const otherQuests = userQuests
      .filter(uq => !knownIds.has(uq.questId))
      .map(uq => {
        const fallbackDef = FALLBACK_QUESTS.find(f => f.id === uq.questId);
        return {
          id: uq.questId,
          title: fallbackDef?.title ?? 'Quête',
          description: fallbackDef?.description ?? '',
          type: fallbackDef?.type ?? uq.questId.split('_')[0] ?? 'UNKNOWN',
          target: uq.target,
          rewardTokens: 5,
          rewardBoosters: 0,
          progress: uq.progress,
          completed: uq.completed,
          rewardClaimed: uq.rewardClaimed,
          isDaily: true,
        };
      });

    // --- 4. If absolutely nothing exists, return stat-based fallback ---
    const allQuests = [...daily, ...permanent, ...otherQuests];
    if (allQuests.length === 0) {
      const fallback = FALLBACK_QUESTS.map((q) => {
        let progress = 0;
        if (q.type === 'booster_count') {
          progress = user?.totalBoostersOpened ?? 0;
        } else if (q.type === 'recycle_count') {
          progress = user?.totalRecycles ?? 0;
        } else if (q.type === 'unique_count') {
          progress = user?.totalCardsObtained ?? 0;
        }
        return {
          ...q,
          progress: Math.min(progress, q.target),
          completed: progress >= q.target,
        };
      });
      console.log(`[quests API] using fallback (${fallback.length} quests)`);
      return NextResponse.json({ quests: fallback });
    }

    console.log(`[quests API] returning ${allQuests.length} quests`);
    return NextResponse.json({ quests: allQuests });
  } catch (error) {
    console.error('Quests error:', error);
    return NextResponse.json({ error: 'Erreur lors de la récupération des quêtes' }, { status: 500 });
  }
}
