import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken, getTokenFromHeader } from '@/lib/auth';
import { FALLBACK_QUESTS } from '@/data/fallbackQuests';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  try {
    const token = getTokenFromHeader(request.headers.get('authorization') || '');
    if (!token) {
      return NextResponse.json({ error: 'Non authentifié' }, { status: 401 });
    }

    const decoded = verifyToken(token);
    if (!decoded) {
      return NextResponse.json({ error: 'Token invalide' }, { status: 401 });
    }

    // Fetch user stats for progress tracking on fallback quests
    const user = await prisma.user.findUnique({
      where: { id: decoded.userId },
      select: {
        totalBoostersOpened: true,
        totalRecycles: true,
        totalCardsObtained: true,
      },
    });

    // Fetch daily quests generated by cron (those with date key pattern)
    const userQuests = await prisma.userQuest.findMany({
      where: { userId: decoded.userId },
      orderBy: { createdAt: 'desc' },
    });

    // Also fetch pool metadata for each quest
    const poolKeys = [...new Set(userQuests.map((q) => {
      const parts = q.questId.split('_');
      return parts.slice(0, -1).join('_');
    }).filter(Boolean))];

    const poolQuests = poolKeys.length > 0
      ? await prisma.questPool.findMany({ where: { key: { in: poolKeys } } })
      : [];

    const poolMap = new Map(poolQuests.map((p) => [p.key, p]));

    const dailyQuests = userQuests
      .filter((uq) => uq.questId.includes('_') && uq.questId.split('_').pop()?.length === 8)
      .map((uq) => {
        const poolKey = uq.questId.split('_').slice(0, -1).join('_');
        const pool = poolMap.get(poolKey);
        return {
          id: uq.questId,
          title: pool?.title ?? 'Quête',
          description: pool?.description ?? '',
          type: pool?.type ?? 'UNKNOWN',
          target: uq.target,
          rewardTokens: 5,
          progress: uq.progress,
          completed: uq.completed,
          rewardClaimed: uq.rewardClaimed,
          isDaily: true,
        };
      });

    // Fallback: if no daily quests exist, return hardcoded quests with real progress
    if (dailyQuests.length === 0) {
      const fallback = FALLBACK_QUESTS.map((q) => {
        let progress = 0;
        if (q.type === 'booster_count') {
          progress = user?.totalBoostersOpened ?? 0;
        } else if (q.type === 'recycle_count') {
          progress = user?.totalRecycles ?? 0;
        } else if (q.type === 'unique_count') {
          progress = user?.totalCardsObtained ?? 0;
        }
        return {
          ...q,
          progress: Math.min(progress, q.target),
          completed: progress >= q.target,
        };
      });
      return NextResponse.json({ quests: fallback });
    }

    return NextResponse.json({ quests: dailyQuests });
  } catch (error) {
    console.error('Quests error:', error);
    return NextResponse.json({ error: 'Erreur lors de la récupération des quêtes' }, { status: 500 });
  }
}
